from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Sequence

import pandas as pd

from src.m39x3g_a.control_design import (
    build_grid_disrupted_control,
    build_rigidity_disrupted_control,
    build_coupled_structural_disruption_control,
)
from src.m39x3g_a.metrics import build_diagnostic_row
from src.m39x3g_a.resampling import bootstrap_comparison, TypeBRuleConfig


@dataclass(slots=True)
class BoundaryScanRow:
    control_family: str
    scan_type: str

    grid_scale: float | None = None
    rigidity_scale: float | None = None
    grid_noise_pct: float | None = None
    rigidity_noise_pct: float | None = None

    n_rows: int = 0
    separation_margin_point: float = 0.0
    separation_margin_mean: float = 0.0
    separation_margin_ci_low: float | None = None
    separation_margin_ci_high: float | None = None
    separation_ratio_mean: float = 0.0
    assignment_score_mean: float = 0.0
    stability_score_mean: float = 0.0
    type_B_like_pattern_detected: bool = False
    notes: str = ""


def _default_type_b_rules() -> TypeBRuleConfig:
    return TypeBRuleConfig()


def _evaluate_single_control_variant(
    *,
    original_df: pd.DataFrame,
    control_df: pd.DataFrame,
    control_family: str,
    feature_columns: Sequence[str],
    n_resamples: int,
    seed: int,
    distance_metric: str,
    rules: TypeBRuleConfig,
):
    comparison_id = f"original_vs_{control_family}"

    resampling = bootstrap_comparison(
        run_id="boundary_scan",
        control_family=control_family,
        comparison_id=comparison_id,
        left_df=original_df,
        right_df=control_df,
        feature_columns=feature_columns,
        n_resamples=n_resamples,
        seed=seed,
        distance_metric=distance_metric,
        rules=rules,
    )

    diagnostic = build_diagnostic_row(
        run_id="boundary_scan",
        feature_space_version="v_current_baseline",
        decision_rule_version="boundary_scan_v1",
        control_family=control_family,
        comparison_id=comparison_id,
        left_df=original_df,
        right_df=control_df,
        feature_columns=feature_columns,
        stability_score=resampling.stability_score,
        type_B_like_pattern_detected=resampling.type_B_like_pattern_detected,
        interpretation="Boundary scan diagnostic.",
        distance_metric=distance_metric,
        warning_flag=False,
        notes="Generated by control_boundary_analysis.py",
    )

    return diagnostic, resampling


def _row_from_results(
    *,
    control_family: str,
    scan_type: str,
    diagnostic,
    resampling,
    grid_scale: float | None = None,
    rigidity_scale: float | None = None,
    grid_noise_pct: float | None = None,
    rigidity_noise_pct: float | None = None,
    notes: str = "",
) -> BoundaryScanRow:
    ci_low = resampling.separation_margin_ci[0] if resampling.separation_margin_ci is not None else None
    ci_high = resampling.separation_margin_ci[1] if resampling.separation_margin_ci is not None else None

    return BoundaryScanRow(
        control_family=control_family,
        scan_type=scan_type,
        grid_scale=grid_scale,
        rigidity_scale=rigidity_scale,
        grid_noise_pct=grid_noise_pct,
        rigidity_noise_pct=rigidity_noise_pct,
        n_rows=diagnostic.n_right,
        separation_margin_point=diagnostic.separation_margin,
        separation_margin_mean=resampling.separation_margin_mean,
        separation_margin_ci_low=ci_low,
        separation_margin_ci_high=ci_high,
        separation_ratio_mean=resampling.separation_ratio_mean,
        assignment_score_mean=resampling.assignment_score_mean,
        stability_score_mean=resampling.stability_score,
        type_B_like_pattern_detected=resampling.type_B_like_pattern_detected,
        notes=notes,
    )


def scan_k1a_grid_boundary(
    *,
    original_df: pd.DataFrame,
    base_df: pd.DataFrame,
    feature_columns: Sequence[str],
    grid_scales: Sequence[float] = (1.10, 1.20, 1.30, 1.40),
    grid_noise_pct: float = 0.10,
    n_resamples: int = 100,
    seed: int = 1729,
    distance_metric: str = "euclidean",
    rules: TypeBRuleConfig | None = None,
) -> pd.DataFrame:
    if rules is None:
        rules = _default_type_b_rules()

    rows: list[BoundaryScanRow] = []

    for i, grid_scale in enumerate(grid_scales):
        control_df = build_grid_disrupted_control(
            base_df,
            control_family="K1a",
            grid_scale=grid_scale,
            grid_noise_pct=grid_noise_pct,
            seed=seed + i,
        )
        diagnostic, resampling = _evaluate_single_control_variant(
            original_df=original_df,
            control_df=control_df,
            control_family="K1a",
            feature_columns=feature_columns,
            n_resamples=n_resamples,
            seed=seed + i,
            distance_metric=distance_metric,
            rules=rules,
        )
        rows.append(
            _row_from_results(
                control_family="K1a",
                scan_type="grid_boundary",
                diagnostic=diagnostic,
                resampling=resampling,
                grid_scale=grid_scale,
                grid_noise_pct=grid_noise_pct,
                notes="Grid-disrupted control boundary scan.",
            )
        )

    return pd.DataFrame([asdict(r) for r in rows])


def scan_k2a_rigidity_boundary(
    *,
    original_df: pd.DataFrame,
    base_df: pd.DataFrame,
    feature_columns: Sequence[str],
    rigidity_scales: Sequence[float] = (0.90, 0.80, 0.70, 0.60),
    rigidity_noise_pct: float = 0.10,
    n_resamples: int = 100,
    seed: int = 1729,
    distance_metric: str = "euclidean",
    rules: TypeBRuleConfig | None = None,
) -> pd.DataFrame:
    if rules is None:
        rules = _default_type_b_rules()

    rows: list[BoundaryScanRow] = []

    for i, rigidity_scale in enumerate(rigidity_scales):
        control_df = build_rigidity_disrupted_control(
            base_df,
            control_family="K2a",
            rigidity_scale=rigidity_scale,
            rigidity_noise_pct=rigidity_noise_pct,
            seed=seed + i,
        )
        diagnostic, resampling = _evaluate_single_control_variant(
            original_df=original_df,
            control_df=control_df,
            control_family="K2a",
            feature_columns=feature_columns,
            n_resamples=n_resamples,
            seed=seed + i,
            distance_metric=distance_metric,
            rules=rules,
        )
        rows.append(
            _row_from_results(
                control_family="K2a",
                scan_type="rigidity_boundary",
                diagnostic=diagnostic,
                resampling=resampling,
                rigidity_scale=rigidity_scale,
                rigidity_noise_pct=rigidity_noise_pct,
                notes="Rigidity-disrupted control boundary scan.",
            )
        )

    return pd.DataFrame([asdict(r) for r in rows])


def scan_k3a_coupled_boundary(
    *,
    original_df: pd.DataFrame,
    base_df: pd.DataFrame,
    feature_columns: Sequence[str],
    grid_scales: Sequence[float] = (1.10, 1.20, 1.30),
    rigidity_scales: Sequence[float] = (0.90, 0.80, 0.70),
    grid_noise_pct: float = 0.10,
    rigidity_noise_pct: float = 0.10,
    n_resamples: int = 100,
    seed: int = 1729,
    distance_metric: str = "euclidean",
    rules: TypeBRuleConfig | None = None,
) -> pd.DataFrame:
    if rules is None:
        rules = _default_type_b_rules()

    rows: list[BoundaryScanRow] = []
    k = 0

    for grid_scale in grid_scales:
        for rigidity_scale in rigidity_scales:
            control_df = build_coupled_structural_disruption_control(
                base_df,
                control_family="K3a",
                grid_scale=grid_scale,
                rigidity_scale=rigidity_scale,
                grid_noise_pct=grid_noise_pct,
                rigidity_noise_pct=rigidity_noise_pct,
                seed=seed + k,
            )
            diagnostic, resampling = _evaluate_single_control_variant(
                original_df=original_df,
                control_df=control_df,
                control_family="K3a",
                feature_columns=feature_columns,
                n_resamples=n_resamples,
                seed=seed + k,
                distance_metric=distance_metric,
                rules=rules,
            )
            rows.append(
                _row_from_results(
                    control_family="K3a",
                    scan_type="coupled_boundary",
                    diagnostic=diagnostic,
                    resampling=resampling,
                    grid_scale=grid_scale,
                    rigidity_scale=rigidity_scale,
                    grid_noise_pct=grid_noise_pct,
                    rigidity_noise_pct=rigidity_noise_pct,
                    notes="Coupled structural disruption boundary scan.",
                )
            )
            k += 1

    return pd.DataFrame([asdict(r) for r in rows])


def build_full_boundary_scan(
    *,
    original_df: pd.DataFrame,
    base_df: pd.DataFrame,
    feature_columns: Sequence[str],
    n_resamples: int = 100,
    seed: int = 1729,
    distance_metric: str = "euclidean",
    rules: TypeBRuleConfig | None = None,
) -> pd.DataFrame:
    if rules is None:
        rules = _default_type_b_rules()

    df_k1 = scan_k1a_grid_boundary(
        original_df=original_df,
        base_df=base_df,
        feature_columns=feature_columns,
        n_resamples=n_resamples,
        seed=seed,
        distance_metric=distance_metric,
        rules=rules,
    )
    df_k2 = scan_k2a_rigidity_boundary(
        original_df=original_df,
        base_df=base_df,
        feature_columns=feature_columns,
        n_resamples=n_resamples,
        seed=seed + 100,
        distance_metric=distance_metric,
        rules=rules,
    )
    df_k3 = scan_k3a_coupled_boundary(
        original_df=original_df,
        base_df=base_df,
        feature_columns=feature_columns,
        n_resamples=n_resamples,
        seed=seed + 200,
        distance_metric=distance_metric,
        rules=rules,
    )

    return pd.concat([df_k1, df_k2, df_k3], axis=0, ignore_index=True)
