#!/usr/bin/env python3
"""Build the QSB-ARTIFACT01-DWH-A sandbox artifact registry dry run."""

from __future__ import annotations

import argparse
import hashlib
import json
import mimetypes
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from textwrap import dedent


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = Path("scripts/qsb_artifact01_dwh_a/qsb_artifact01_dwh_a.py")
SCHEMA_PATH = REPO_ROOT / "scripts/qsb_artifact01_dwh_a/schema.sql"
INPUT_DIR = REPO_ROOT / "runs/QSB-MAP01-DWH-A"
OUTPUT_DIR = REPO_ROOT / "runs/QSB-ARTIFACT01-DWH-A"
DB_PATH = OUTPUT_DIR / "qsb_artifact01.sqlite"
GENERATOR_NAME = "qsb_artifact01_dwh_a.py"
GENERATOR_VERSION = "0.1"
RUN_ID = "QSB-ARTIFACT01-DWH-A"
SOURCE_RUN_ID = "QSB-MAP01-DWH-A"
CLAIM_BOUNDARY_SUMMARY = (
    "Sandbox artifact metadata registry only; no production mutation, no physics "
    "claim, no spacetime claim, no causality claim, and no RELALG computation."
)
DEFAULT_ADMISSIBLE_USE = (
    "Registered sandbox artifact generated by or associated with QSB-MAP01-DWH-A "
    "for project orientation, metadata, validation, or documentation context."
)
DEFAULT_FORBIDDEN_USE = (
    "Do not present this artifact as evidence for physical causality, spacetime "
    "emergence, validated physics, or QSB confirmation."
)
FORBIDDEN_CONFIRMATION_WORDING = [
    "proves QSB",
    "proves spacetime",
    "establishes causality",
    "confirms emergent spacetime",
    "validates physical theory",
    "demonstrates new gravity",
]


EXPECTED_ARTIFACTS = [
    {
        "filename": "qsb_map01.sqlite",
        "artifact_id": "QSB-ART-MAP01-SQLITE-0001",
        "title": "QSB-MAP01 SQLite mart",
        "artifact_type": "sqlite",
        "semantic_role": "generated_mart",
        "visibility": "internal",
        "status": "registered",
        "overclaim_risk": "medium",
        "admissible_use": "Sandbox SQLite mart for canonical QSB-MAP01 mindmap records and export generation.",
        "forbidden_use": "Do not treat this sandbox mart as production DWH, physical evidence, or validated RELALG computation.",
    },
    {
        "filename": "qsb_map01_seed_manifest.json",
        "artifact_id": "QSB-ART-MAP01-SEEDMANIFEST-0001",
        "title": "QSB-MAP01 seed manifest",
        "artifact_type": "json",
        "semantic_role": "seed_manifest",
        "visibility": "internal",
        "status": "registered",
        "overclaim_risk": "medium",
    },
    {
        "filename": "qsb_map01_validation_report.json",
        "artifact_id": "QSB-ART-MAP01-VALIDATION-0001",
        "title": "QSB-MAP01 validation report",
        "artifact_type": "json",
        "semantic_role": "validation_output",
        "visibility": "internal",
        "status": "registered",
        "overclaim_risk": "medium",
    },
    {
        "filename": "qsb_map01.mmd",
        "artifact_id": "QSB-ART-MAP01-MMD-0001",
        "title": "QSB-MAP01 Mermaid mindmap source",
        "artifact_type": "mermaid",
        "semantic_role": "mindmap_source",
        "visibility": "internal",
        "status": "registered",
        "overclaim_risk": "high",
        "admissible_use": "Mermaid mindmap source generated from QSB-MAP01-DWH-A database records.",
        "forbidden_use": "Do not present the mindmap as evidence for spacetime emergence, physical causality, or validated physics.",
    },
    {
        "filename": "qsb_map01.md",
        "artifact_id": "QSB-ART-MAP01-MD-0001",
        "title": "QSB-MAP01 Markdown overview",
        "artifact_type": "markdown",
        "semantic_role": "project_documentation",
        "visibility": "internal",
        "status": "registered",
        "overclaim_risk": "high",
        "admissible_use": "Markdown overview generated from QSB-MAP01-DWH-A database records.",
        "forbidden_use": "Do not present the overview as a validated physical result or QSB confirmation.",
    },
    {
        "filename": "qsb_map01_claim_boundary_report.md",
        "artifact_id": "QSB-ART-MAP01-CLAIMREPORT-0001",
        "title": "QSB-MAP01 claim boundary report",
        "artifact_type": "markdown",
        "semantic_role": "claim_boundary_output",
        "visibility": "internal",
        "status": "registered",
        "overclaim_risk": "high",
    },
    {
        "filename": "QSB-MAP01-DWH-A_RUN_SUMMARY.md",
        "artifact_id": "QSB-ART-MAP01-RUNSUMMARY-0001",
        "title": "QSB-MAP01 run summary",
        "artifact_type": "markdown",
        "semantic_role": "run_summary",
        "visibility": "internal",
        "status": "registered",
        "overclaim_risk": "medium",
    },
]

BASE_ALIASES = ["QSB-MAP01", "project map", "Projektlandkarte", "mindmap", "DWH mindmap"]
EXTRA_ALIASES = {
    "qsb_map01.mmd": ["Mermaid", "Mermaid mindmap", "map source"],
    "qsb_map01.md": ["Markdown overview", "project overview", "Projektübersicht"],
    "qsb_map01_claim_boundary_report.md": [
        "claim boundary report",
        "Claim-Grenzen",
        "overclaim risk",
    ],
}
RELATION_RULES = [
    ("qsb_map01.md", "qsb_map01.mmd", "derived_from", "Markdown overview derived from Mermaid source context."),
    ("qsb_map01_claim_boundary_report.md", "qsb_map01.sqlite", "derived_from", "Claim boundary report derived from SQLite mart context."),
    ("qsb_map01_validation_report.json", "qsb_map01.sqlite", "documents", "Validation report documents the SQLite mart run."),
    ("QSB-MAP01-DWH-A_RUN_SUMMARY.md", "qsb_map01.sqlite", "summarizes", "Run summary summarizes the SQLite mart run."),
    ("qsb_map01_seed_manifest.json", "qsb_map01.sqlite", "documents", "Seed manifest documents the SQLite mart run inputs and outputs."),
]
REPORT_PATHS = {
    "validation": OUTPUT_DIR / "qsb_artifact01_validation_report.json",
    "registry": OUTPUT_DIR / "qsb_artifact01_registry_report.md",
    "claim_risk": OUTPUT_DIR / "qsb_artifact01_claim_risk_report.md",
    "downloads": OUTPUT_DIR / "qsb_artifact01_downloads_report.md",
    "summary": OUTPUT_DIR / "QSB-ARTIFACT01-DWH-A_RUN_SUMMARY.md",
    "manifest": OUTPUT_DIR / "qsb_artifact01_seed_manifest.json",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def normalize_excerpt(text: str, length: int = 500) -> str:
    return " ".join(text.split())[:length]


def language_for_alias(alias: str) -> str:
    if any(ch in alias for ch in "äöüÄÖÜß") or "Grenzen" in alias:
        return "de"
    return "en"


def connect_fresh_database(force: bool) -> sqlite3.Connection:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if DB_PATH.exists() and not force:
        raise FileExistsError(f"{rel(DB_PATH)} already exists; rerun with --force to replace sandbox outputs.")
    if force:
        for path in OUTPUT_DIR.iterdir():
            if path.is_file():
                path.unlink()
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA foreign_keys = ON")
    con.executescript(SCHEMA_PATH.read_text(encoding="utf-8"))
    return con


def insert_artifact(con: sqlite3.Connection, spec: dict[str, str], timestamp: str) -> dict[str, str | int]:
    path = INPUT_DIR / spec["filename"]
    canonical_path = rel(path)
    content_hash = sha256_file(path)
    mime_type = mimetypes.guess_type(path.name)[0]
    if path.suffix == ".mmd":
        mime_type = "text/vnd.mermaid"
    record = {
        **spec,
        "path": path,
        "canonical_path": canonical_path,
        "content_hash": content_hash,
        "mime_type": mime_type,
        "file_extension": path.suffix,
        "size_bytes": path.stat().st_size,
    }
    con.execute(
        """
        INSERT INTO qsb_artifact (
            artifact_id, title, artifact_type, semantic_role, mime_type,
            file_extension, canonical_path, uri, content_hash, hash_algorithm,
            size_bytes, created_at, created_by, source_system, status, visibility,
            notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            spec["artifact_id"],
            spec["title"],
            spec["artifact_type"],
            spec["semantic_role"],
            mime_type,
            path.suffix,
            canonical_path,
            canonical_path,
            content_hash,
            "sha256",
            path.stat().st_size,
            timestamp,
            GENERATOR_NAME,
            SOURCE_RUN_ID,
            spec["status"],
            spec["visibility"],
            "Registered by QSB-ARTIFACT01-DWH-A sandbox artifact registry dry run.",
        ),
    )
    con.execute(
        """
        INSERT INTO qsb_artifact_version (
            artifact_version_id, artifact_id, version, canonical_path,
            content_hash, generated_at, generator_name, generator_version,
            supersedes_version_id, change_summary, status
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            f"{spec['artifact_id']}-V001",
            spec["artifact_id"],
            "v0.1",
            canonical_path,
            content_hash,
            timestamp,
            GENERATOR_NAME,
            GENERATOR_VERSION,
            None,
            "Initial sandbox artifact registry dry-run version.",
            "active",
        ),
    )
    con.execute(
        """
        INSERT INTO qsb_artifact_lineage (
            lineage_id, artifact_id, source_type, source_ref, source_artifact_id,
            source_table, source_query, run_id, evidence_role,
            transformation_summary, status
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            f"{spec['artifact_id']}-LIN-001",
            spec["artifact_id"],
            "generated_export",
            SOURCE_RUN_ID,
            None,
            None,
            None,
            SOURCE_RUN_ID,
            "metadata_context",
            "Generated by QSB-MAP01-DWH-A sandbox mart/export dry run.",
            "active",
        ),
    )
    return record


def insert_aliases(con: sqlite3.Connection, record: dict[str, str | int]) -> None:
    artifact_id = str(record["artifact_id"])
    aliases = BASE_ALIASES + EXTRA_ALIASES.get(str(record["filename"]), [])
    for idx, alias in enumerate(aliases, start=1):
        con.execute(
            """
            INSERT INTO qsb_artifact_alias (
                alias_id, artifact_id, alias, language, alias_type, status
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                f"{artifact_id}-ALIAS-{idx:03d}",
                artifact_id,
                alias,
                language_for_alias(alias),
                "search_alias",
                "active",
            ),
        )


def insert_claim_boundary(con: sqlite3.Connection, record: dict[str, str | int]) -> None:
    artifact_id = str(record["artifact_id"])
    admissible_use = str(record.get("admissible_use") or DEFAULT_ADMISSIBLE_USE)
    forbidden_use = str(record.get("forbidden_use") or DEFAULT_FORBIDDEN_USE)
    con.execute(
        """
        INSERT INTO qsb_artifact_claim_boundary (
            boundary_id, artifact_id, admissible_use, forbidden_use,
            overclaim_risk, review_status, notes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            f"{artifact_id}-BOUNDARY-001",
            artifact_id,
            admissible_use,
            forbidden_use,
            str(record["overclaim_risk"]),
            "unreviewed",
            "Sandbox claim boundary; human review pending before any broader use.",
        ),
    )


def insert_review(con: sqlite3.Connection, record: dict[str, str | int], timestamp: str) -> None:
    artifact_id = str(record["artifact_id"])
    con.execute(
        """
        INSERT INTO qsb_artifact_review (
            review_id, artifact_id, reviewer_role, review_status, review_note,
            reviewed_at
        )
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            f"{artifact_id}-REVIEW-001",
            artifact_id,
            "implementation_self_check",
            "unreviewed",
            "Registered by sandbox artifact registry; human review pending.",
            timestamp,
        ),
    )


def insert_text_index(con: sqlite3.Connection, record: dict[str, str | int]) -> None:
    artifact_id = str(record["artifact_id"])
    path = Path(record["path"])
    suffix = path.suffix.lower()
    if suffix == ".sqlite":
        text_role = "binary_notice"
        text_hash = None
        excerpt = "SQLite binary registered; no text extraction in this dry run."
        extraction_method = None
        extraction_status = "not_text_extractable"
    elif suffix in {".md", ".mmd"}:
        text = path.read_text(encoding="utf-8")
        text_role = "full_text"
        text_hash = sha256_text(text)
        excerpt = normalize_excerpt(text)
        extraction_method = "direct_text_read"
        extraction_status = "extracted"
    elif suffix == ".json":
        text = path.read_text(encoding="utf-8")
        text_role = "summary"
        text_hash = sha256_text(text)
        excerpt = normalize_excerpt(text)
        extraction_method = "direct_text_read"
        extraction_status = "extracted"
    elif suffix == ".sql":
        text = path.read_text(encoding="utf-8")
        text_role = "full_text"
        text_hash = sha256_text(text)
        excerpt = normalize_excerpt(text)
        extraction_method = "direct_text_read"
        extraction_status = "extracted"
    else:
        text_role = "unclassified"
        text_hash = None
        excerpt = "No text extraction rule for this artifact extension."
        extraction_method = None
        extraction_status = "not_text_extractable"
    con.execute(
        """
        INSERT INTO qsb_artifact_text_index (
            text_index_id, artifact_id, text_role, language, extracted_text_path,
            text_hash, excerpt, extraction_method, extraction_status
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            f"{artifact_id}-TEXT-001",
            artifact_id,
            text_role,
            "en",
            str(record["canonical_path"]) if extraction_status == "extracted" else None,
            text_hash,
            excerpt,
            extraction_method,
            extraction_status,
        ),
    )


def insert_export(con: sqlite3.Connection, record: dict[str, str | int], timestamp: str) -> None:
    artifact_id = str(record["artifact_id"])
    extension = str(record["file_extension"]).lstrip(".") or str(record["artifact_type"])
    label = f"{record['title']} ({extension})"
    con.execute(
        """
        INSERT INTO qsb_artifact_export (
            export_id, artifact_id, export_type, output_path, generated_at,
            generator_name, generator_version, content_hash, download_label, status
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            f"{artifact_id}-EXPORT-001",
            artifact_id,
            extension,
            str(record["canonical_path"]),
            timestamp,
            GENERATOR_NAME,
            GENERATOR_VERSION,
            str(record["content_hash"]),
            label,
            "registered_internal_export",
        ),
    )


def insert_relations(con: sqlite3.Connection, records_by_filename: dict[str, dict[str, str | int]]) -> None:
    for idx, (source_name, target_name, relation_type, label) in enumerate(RELATION_RULES, start=1):
        source = records_by_filename.get(source_name)
        target = records_by_filename.get(target_name)
        if not source or not target:
            continue
        con.execute(
            """
            INSERT INTO qsb_artifact_relation (
                relation_id, source_artifact_id, target_artifact_id,
                relation_type, relation_label, status
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                f"QSB-ARTIFACT01-REL-{idx:03d}",
                str(source["artifact_id"]),
                str(target["artifact_id"]),
                relation_type,
                label,
                "active",
            ),
        )


def count_rows(con: sqlite3.Connection) -> dict[str, int]:
    tables = [
        "qsb_artifact",
        "qsb_artifact_version",
        "qsb_artifact_lineage",
        "qsb_artifact_relation",
        "qsb_artifact_alias",
        "qsb_artifact_text_index",
        "qsb_artifact_claim_boundary",
        "qsb_artifact_export",
        "qsb_artifact_review",
        "qsb_artifact_validation_result",
    ]
    return {table: int(con.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]) for table in tables}


def scalar(con: sqlite3.Connection, query: str, params: tuple[object, ...] = ()) -> int:
    return int(con.execute(query, params).fetchone()[0])


def add_result(
    results: list[dict[str, str]],
    rule_id: str,
    severity: str,
    status: str,
    message: str,
    timestamp: str,
) -> None:
    results.append(
        {
            "validation_id": f"QSB-ARTIFACT01-VAL-{rule_id}",
            "rule_id": rule_id,
            "severity": severity,
            "status": status,
            "message": message,
            "checked_at": timestamp,
        }
    )


def validate(con: sqlite3.Connection, missing_inputs: list[str], timestamp: str) -> list[dict[str, str]]:
    results: list[dict[str, str]] = []
    artifact_count = scalar(con, "SELECT COUNT(*) FROM qsb_artifact")
    add_result(results, "V01", "error", "pass" if scalar(con, "SELECT COUNT(*) FROM qsb_artifact WHERE content_hash = '' OR content_hash IS NULL") == 0 else "fail", "Every artifact has content_hash.", timestamp)
    add_result(results, "V02", "error", "pass" if scalar(con, "SELECT COUNT(*) FROM qsb_artifact WHERE canonical_path = '' OR canonical_path IS NULL") == 0 else "fail", "Every artifact has canonical_path.", timestamp)
    add_result(results, "V03", "error", "pass" if scalar(con, "SELECT COUNT(*) FROM qsb_artifact WHERE artifact_type = '' OR semantic_role = ''") == 0 else "fail", "Every artifact has artifact_type and semantic_role.", timestamp)
    add_result(results, "V04", "error", "pass" if scalar(con, "SELECT COUNT(*) FROM qsb_artifact_version WHERE content_hash = '' OR content_hash IS NULL") == 0 else "fail", "Every artifact version has content_hash.", timestamp)
    missing_versions = scalar(con, "SELECT COUNT(*) FROM qsb_artifact AS a WHERE NOT EXISTS (SELECT 1 FROM qsb_artifact_version AS v WHERE v.artifact_id = a.artifact_id)")
    add_result(results, "V05", "error", "pass" if missing_versions == 0 else "fail", "Every registered artifact has at least one version.", timestamp)
    missing_boundaries = scalar(con, "SELECT COUNT(*) FROM qsb_artifact AS a WHERE NOT EXISTS (SELECT 1 FROM qsb_artifact_claim_boundary AS b WHERE b.artifact_id = a.artifact_id)")
    add_result(results, "V06", "error", "pass" if missing_boundaries == 0 else "fail", "Every artifact has a claim boundary.", timestamp)
    high_risk_missing_forbidden = scalar(con, "SELECT COUNT(*) FROM qsb_artifact_claim_boundary WHERE overclaim_risk IN ('high', 'critical') AND (forbidden_use = '' OR forbidden_use IS NULL)")
    add_result(results, "V07", "error", "pass" if high_risk_missing_forbidden == 0 else "fail", "Every high-risk artifact has forbidden_use filled.", timestamp)
    export_without_context = scalar(
        con,
        """
        SELECT COUNT(*)
        FROM qsb_artifact_export AS e
        WHERE (e.generator_name IS NULL OR e.generator_name = '')
          AND NOT EXISTS (
              SELECT 1 FROM qsb_artifact_lineage AS l
              WHERE l.artifact_id = e.artifact_id
          )
        """,
    )
    add_result(results, "V08", "error", "pass" if export_without_context == 0 else "fail", "Every generated export has generator metadata or lineage.", timestamp)
    broken_relations = scalar(
        con,
        """
        SELECT COUNT(*)
        FROM qsb_artifact_relation AS r
        LEFT JOIN qsb_artifact AS s ON s.artifact_id = r.source_artifact_id
        LEFT JOIN qsb_artifact AS t ON t.artifact_id = r.target_artifact_id
        WHERE s.artifact_id IS NULL OR t.artifact_id IS NULL
        """,
    )
    add_result(results, "V09", "error", "pass" if broken_relations == 0 else "fail", "Every derived relation references existing artifacts.", timestamp)
    add_result(results, "V10", "error", "pass" if scalar(con, "SELECT COUNT(*) FROM qsb_artifact_text_index WHERE extraction_status = '' OR extraction_status IS NULL") == 0 else "fail", "Every text-indexed artifact has extraction_status.", timestamp)
    missing_reviews = scalar(con, "SELECT COUNT(*) FROM qsb_artifact AS a WHERE NOT EXISTS (SELECT 1 FROM qsb_artifact_review AS r WHERE r.artifact_id = a.artifact_id)")
    add_result(results, "V11", "error", "pass" if missing_reviews == 0 else "fail", "Every registered artifact has a review record.", timestamp)
    offending = []
    for phrase in FORBIDDEN_CONFIRMATION_WORDING:
        pattern = f"%{phrase.lower()}%"
        count = scalar(
            con,
            """
            SELECT COUNT(*)
            FROM (
                SELECT title AS text_value FROM qsb_artifact
                UNION ALL SELECT COALESCE(notes, '') FROM qsb_artifact
                UNION ALL SELECT admissible_use FROM qsb_artifact_claim_boundary
                UNION ALL SELECT COALESCE(transformation_summary, '') FROM qsb_artifact_lineage
            )
            WHERE lower(text_value) LIKE ?
            """,
            (pattern,),
        )
        if count:
            offending.append(phrase)
    add_result(results, "V12", "error", "pass" if not offending else "fail", "No non-warning artifact text contains forbidden confirmation wording.", timestamp)
    bad_exports = scalar(con, "SELECT COUNT(*) FROM qsb_artifact_export WHERE content_hash = '' OR content_hash IS NULL OR output_path = '' OR output_path IS NULL")
    add_result(results, "V13", "error", "pass" if bad_exports == 0 else "fail", "Every export has content_hash and output_path.", timestamp)
    missing_run_id = scalar(con, "SELECT COUNT(*) FROM qsb_artifact_lineage WHERE source_type = 'generated_export' AND (run_id = '' OR run_id IS NULL)")
    add_result(results, "V14", "error", "pass" if missing_run_id == 0 else "fail", "Every artifact linked to generated_export has run_id.", timestamp)
    if missing_inputs:
        add_result(results, "V15", "warning", "warning", f"Missing expected QSB-MAP01-DWH-A files: {', '.join(missing_inputs)}.", timestamp)
    else:
        add_result(results, "V15", "warning", "pass", "No expected QSB-MAP01-DWH-A files are missing.", timestamp)

    for result in results:
        con.execute(
            """
            INSERT INTO qsb_artifact_validation_result (
                validation_id, rule_id, severity, status, message, checked_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                result["validation_id"],
                result["rule_id"],
                result["severity"],
                result["status"],
                result["message"],
                result["checked_at"],
            ),
        )
    assert artifact_count == scalar(con, "SELECT COUNT(*) FROM qsb_artifact")
    return results


def rows(con: sqlite3.Connection, query: str) -> list[sqlite3.Row]:
    return list(con.execute(query))


def markdown_table(headers: list[str], body: list[list[object]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for row in body:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(lines)


def write_registry_report(con: sqlite3.Connection, timestamp: str) -> None:
    artifacts = rows(con, "SELECT artifact_id, title, artifact_type, semantic_role, canonical_path, size_bytes, status FROM qsb_artifact ORDER BY artifact_id")
    counts = rows(con, "SELECT artifact_type, COUNT(*) AS count FROM qsb_artifact GROUP BY artifact_type ORDER BY artifact_type")
    lineage = rows(con, "SELECT source_type, source_ref, run_id, COUNT(*) AS count FROM qsb_artifact_lineage GROUP BY source_type, source_ref, run_id ORDER BY source_type")
    text_counts = rows(con, "SELECT extraction_status, COUNT(*) AS count FROM qsb_artifact_text_index GROUP BY extraction_status ORDER BY extraction_status")
    text = dedent(
        f"""\
        # QSB-ARTIFACT01-DWH-A Registry Report

        Generated at: {timestamp}

        Sandbox status: artifact metadata registry dry run only.

        No production DWH mutation was performed.

        ## Registered Artifacts

        {markdown_table(["artifact_id", "title", "type", "semantic_role", "path", "size_bytes", "status"], [[r["artifact_id"], r["title"], r["artifact_type"], r["semantic_role"], r["canonical_path"], r["size_bytes"], r["status"]] for r in artifacts])}

        ## Artifact Type Counts

        {markdown_table(["artifact_type", "count"], [[r["artifact_type"], r["count"]] for r in counts])}

        ## Lineage Summary

        {markdown_table(["source_type", "source_ref", "run_id", "count"], [[r["source_type"], r["source_ref"], r["run_id"], r["count"]] for r in lineage])}

        ## Text Indexing Summary

        {markdown_table(["extraction_status", "count"], [[r["extraction_status"], r["count"]] for r in text_counts])}
        """
    )
    REPORT_PATHS["registry"].write_text(text, encoding="utf-8")


def write_claim_risk_report(con: sqlite3.Connection, timestamp: str) -> None:
    risk_rows = rows(
        con,
        """
        SELECT a.artifact_id, a.title, a.artifact_type, b.overclaim_risk,
               b.admissible_use, b.forbidden_use, b.review_status
        FROM qsb_artifact AS a
        JOIN qsb_artifact_claim_boundary AS b ON b.artifact_id = a.artifact_id
        WHERE b.overclaim_risk IN ('medium', 'high', 'critical')
        ORDER BY CASE b.overclaim_risk WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END, a.artifact_id
        """,
    )
    text = dedent(
        f"""\
        # QSB-ARTIFACT01-DWH-A Claim Risk Report

        Generated at: {timestamp}

        {markdown_table(["artifact_id", "title", "type", "risk", "admissible_use", "forbidden_use", "review_status"], [[r["artifact_id"], r["title"], r["artifact_type"], r["overclaim_risk"], r["admissible_use"], r["forbidden_use"], r["review_status"]] for r in risk_rows])}
        """
    )
    REPORT_PATHS["claim_risk"].write_text(text, encoding="utf-8")


def write_downloads_report(con: sqlite3.Connection, timestamp: str) -> None:
    download_rows = rows(
        con,
        """
        SELECT e.download_label, e.output_path, e.content_hash, a.visibility,
               r.review_status
        FROM qsb_artifact_export AS e
        JOIN qsb_artifact AS a ON a.artifact_id = e.artifact_id
        JOIN qsb_artifact_review AS r ON r.artifact_id = e.artifact_id
        ORDER BY e.output_path
        """,
    )
    text = dedent(
        f"""\
        # QSB-ARTIFACT01-DWH-A Downloads Report

        Generated at: {timestamp}

        No public publishing authorized. These are registered internal exports only.

        {markdown_table(["download_label", "output_path", "hash", "visibility", "review_status"], [[r["download_label"], r["output_path"], r["content_hash"], r["visibility"], r["review_status"]] for r in download_rows])}
        """
    )
    REPORT_PATHS["downloads"].write_text(text, encoding="utf-8")


def validation_status(results: list[dict[str, str]]) -> str:
    if any(row["status"] == "fail" for row in results):
        return "fail"
    if any(row["status"] == "warning" for row in results):
        return "warning"
    return "pass"


def write_validation_report(
    con: sqlite3.Connection,
    results: list[dict[str, str]],
    missing_inputs: list[str],
    timestamp: str,
) -> None:
    report = {
        "run_id": RUN_ID,
        "timestamp": timestamp,
        "validation_status": validation_status(results),
        "missing_expected_inputs": missing_inputs,
        "results": results,
        "row_counts": count_rows(con),
        "claim_boundary_summary": CLAIM_BOUNDARY_SUMMARY,
    }
    REPORT_PATHS["validation"].write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_run_summary(
    records: list[dict[str, str | int]],
    results: list[dict[str, str]],
    missing_inputs: list[str],
    timestamp: str,
) -> None:
    created = [rel(path) for path in [DB_PATH, *REPORT_PATHS.values()]]
    text = dedent(
        f"""\
        # QSB-ARTIFACT01-DWH-A Run Summary

        Generated at: {timestamp}

        ## Purpose

        Create a sandbox-only SQLite artifact registry dry run for QSB-MAP01-DWH-A generated outputs.

        ## Files Created

        {chr(10).join(f"- {path}" for path in created)}

        ## Inputs Registered

        {chr(10).join(f"- {record['canonical_path']} -> {record['artifact_id']}" for record in records)}

        ## Validation Summary

        Status: {validation_status(results)}

        {chr(10).join(f"- {row['rule_id']}: {row['status']} ({row['severity']}) - {row['message']}" for row in results)}

        ## Missing Inputs

        {chr(10).join(f"- {name}" for name in missing_inputs) if missing_inputs else "- None"}

        ## No Production Mutation Statement

        This run created a standalone sandbox registry under `runs/QSB-ARTIFACT01-DWH-A/` and did not mutate a production DWH, Source-Hub, EXTRACT, META, MAP01, or existing project schema.

        ## No Physics Claim Statement

        This dry run registers artifact metadata only. It introduces no physical, spacetime, causality, RELALG computation, or QSB-confirmation claim.

        ## Next Allowed Step

        Human review may inspect the registry tables, validation report, and claim-risk report before any further metadata integration is considered.
        """
    )
    REPORT_PATHS["summary"].write_text(text, encoding="utf-8")


def write_seed_manifest(
    con: sqlite3.Connection,
    records: list[dict[str, str | int]],
    results: list[dict[str, str]],
    missing_inputs: list[str],
    timestamp: str,
) -> None:
    report_paths = {name: rel(path) for name, path in REPORT_PATHS.items() if name != "manifest"}
    report_hashes = {name: sha256_file(path) for name, path in REPORT_PATHS.items() if name != "manifest" and path.exists()}
    manifest = {
        "run_id": RUN_ID,
        "script_path": str(SCRIPT_PATH),
        "input_directory": rel(INPUT_DIR),
        "output_directory": rel(OUTPUT_DIR),
        "registered_artifacts": [
            {
                "artifact_id": str(record["artifact_id"]),
                "canonical_path": str(record["canonical_path"]),
                "content_hash": str(record["content_hash"]),
                "size_bytes": int(record["size_bytes"]),
                "artifact_type": str(record["artifact_type"]),
                "semantic_role": str(record["semantic_role"]),
            }
            for record in records
        ],
        "missing_expected_inputs": missing_inputs,
        "row_counts_per_table": count_rows(con),
        "generated_report_paths": report_paths,
        "hashes_of_generated_reports": report_hashes,
        "validation_status": validation_status(results),
        "timestamp": timestamp,
        "sandbox_only_claim_boundary_summary": CLAIM_BOUNDARY_SUMMARY,
    }
    REPORT_PATHS["manifest"].write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def build(force: bool) -> None:
    timestamp = utc_now()
    con = connect_fresh_database(force)
    missing_inputs: list[str] = []
    records: list[dict[str, str | int]] = []
    records_by_filename: dict[str, dict[str, str | int]] = {}
    try:
        for spec in EXPECTED_ARTIFACTS:
            path = INPUT_DIR / spec["filename"]
            if not path.exists():
                missing_inputs.append(spec["filename"])
                continue
            record = insert_artifact(con, spec, timestamp)
            insert_aliases(con, record)
            insert_claim_boundary(con, record)
            insert_review(con, record, timestamp)
            insert_text_index(con, record)
            insert_export(con, record, timestamp)
            records.append(record)
            records_by_filename[spec["filename"]] = record
        insert_relations(con, records_by_filename)
        results = validate(con, missing_inputs, timestamp)
        con.commit()
        write_validation_report(con, results, missing_inputs, timestamp)
        write_registry_report(con, timestamp)
        write_claim_risk_report(con, timestamp)
        write_downloads_report(con, timestamp)
        write_run_summary(records, results, missing_inputs, timestamp)
        write_seed_manifest(con, records, results, missing_inputs, timestamp)
    finally:
        con.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace files inside runs/QSB-ARTIFACT01-DWH-A only.",
    )
    args = parser.parse_args()
    build(force=args.force)


if __name__ == "__main__":
    main()
