#!/usr/bin/env python3
"""Prepare EXTRACT03 contracts and guards; perform no extraction or computation."""
from __future__ import annotations
import csv, hashlib, json
from datetime import datetime, timezone
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/"runs/QSB-EXTRACT03/execution_package_preparation"
R1F=ROOT/"runs/QSB-EXTRACT02A-R1F/artifact_consistency_fix_human_freeze_recheck"
INPUTS=[ROOT/"runs/QSB-EXTRACT02A/input/human_freeze_decisions.json",ROOT/"configs/qsb_extract02a_human_freeze_decisions.json"]
BLOCKS={
"R1F":R1F/"01_extract02a_r1f_run_manifest.json","R1":ROOT/"runs/QSB-EXTRACT02A-R1/human_freeze_applied_authorization_recheck/01_extract02a_r1_run_manifest.json","EXTRACT02A":ROOT/"runs/QSB-EXTRACT02A/human_freeze_resolution_authorization_check/01_extract02a_run_manifest.json","EXTRACT02":ROOT/"runs/QSB-EXTRACT02/pre_execution_contract_dwh_gram_tensor_extraction/01_extract02_run_manifest.json","EXTRACT01A":ROOT/"runs/QSB-EXTRACT01A/metadata_gap_prerequisite_resolution_review/01_extract01a_run_manifest.json","EXTRACT01":ROOT/"runs/QSB-EXTRACT01/dwh_based_gram_tensor_extraction_layer_design/01_extract01_run_manifest.json","F3":ROOT/"runs/QSB-INTERFACE01F3/authorized_delta_phi_export_staging_preflight/01_f3_run_manifest.json","L2":ROOT/"runs/QSB-INTERFACE01L2/separate_final_minimaltest_execution_under_j2/01_l2_run_manifest.json","M2":ROOT/"runs/QSB-INTERFACE01M2/result_review_mechanism_interpretation_boundary_after_l2/01_m2_run_manifest.json","N0":ROOT/"runs/QSB-INTERFACE01N0/post_fail_scope_review_feature_n4_extract_path/01_n0_run_manifest.json"}
NAMES={"HF-01":"freeze_psi_or_feature_state_family","HF-02":"freeze_K_construction_mode","HF-03":"freeze_ell0","HF-04":"freeze_epsilon_Gram","HF-05":"freeze_distance_to_strength_transform","HF-06":"freeze_edge_threshold","HF-07":"freeze_kernel_subset","HF-08":"freeze_cluster_protocol","HF-09":"freeze_source_selection_query","HF-10":"freeze_validation_matrix"}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return str(p.relative_to(ROOT))
def load(p):return json.loads(p.read_text(encoding="utf-8"))
def required(v):
    if isinstance(v,str):return not v.strip() or "REQUIRED" in v
    if isinstance(v,list):return not v or any(required(x) for x in v)
    if isinstance(v,dict):return not v or any(required(x) for x in v.values())
    return v is None
def writecsv(name,fields,rows):
    with (OUT/name).open("w",encoding="utf-8",newline="") as f:
        w=csv.DictWriter(f,fieldnames=fields,extrasaction="ignore");w.writeheader();w.writerows(rows)
def get(v,key,default="not_supplied"):
    return v.get(key,default) if isinstance(v,dict) else default

def main():
    if OUT.exists():raise SystemExit(f"Refusing to overwrite: {OUT}")
    required_blocks={"R1F","EXTRACT02","EXTRACT01A","EXTRACT01","F3"}
    missing=[b for b in required_blocks if not BLOCKS[b].is_file()]
    if missing:raise SystemExit("Missing required upstream: "+",".join(missing))
    inp=next((p for p in INPUTS if p.is_file()),None)
    if not inp:raise SystemExit("Missing explicit human-freeze JSON")
    r1f=load(BLOCKS["R1F"])
    if r1f.get("status")!="extract02a_r1f_artifact_consistency_fix_completed_authorized_for_extract03_package_preparation" or r1f.get("authorization_value")!="authorized_to_prepare_extract03_execution_package":raise SystemExit("R1F does not authorize package preparation")
    data=load(inp); decisions=data.get("decisions",[]); by={x.get("freeze_id"):x for x in decisions if isinstance(x,dict)}
    carried=[]; invalid=0; missing_count=0
    for fid,name in NAMES.items():
        d=by.get(fid)
        if not d:missing_count+=1; valid=False; d={}
        else:
            valid=d.get("freeze_item")==name and d.get("decision_status")=="human_approved_frozen" and d.get("human_approval")=="approved" and d.get("blocks_extract03_package") is False and d.get("blocks_actual_execution") is False and not required(d.get("decision_value"))
            if not valid:invalid+=1
        carried.append({"freeze_id":fid,"freeze_item":name,"decision_value":json.dumps(d.get("decision_value","not_supplied"),ensure_ascii=False),"decision_status":d.get("decision_status","not_supplied"),"human_approval":d.get("human_approval","missing"),"blocks_extract03_package":d.get("blocks_extract03_package","not_supplied"),"blocks_actual_execution":d.get("blocks_actual_execution","not_supplied"),"carried_forward_to_extract03":"yes" if valid else "no","package_role":"frozen contract input","validation_status":"pass" if valid else "fail","notes":"No computation in package preparation."})
    approved=sum(x["validation_status"]=="pass" for x in carried)
    material_ok=data.get("material_sensitive_sources_in_first_scope") is False and data.get("material_sensitive_sources_status")=="excluded_pending_separate_source_contract"
    if approved!=10 or missing_count or invalid or not material_ok:raise SystemExit("Invalid human-freeze carry-forward")
    hf=lambda fid:by[fid]["decision_value"]
    hf1,hf2,hf5,hf7,hf8,hf9=hf("HF-01"),hf("HF-02"),hf("HF-05"),hf("HF-07"),hf("HF-08"),hf("HF-09")

    specs=[(b,p,"yes" if b in required_blocks or b=="R1F" else "no") for b,p in BLOCKS.items()]
    specs.append(("HUMAN_FREEZE",inp,"yes"))
    before={rel(p):sha(p) for _,p,_ in specs if p.is_file()}
    inventory=[{"artifact_id":f"E03-A{i:02d}","upstream_block":b,"path":rel(p),"exists":"yes" if p.is_file() else "no","sha256":before.get(rel(p),"missing"),"role":"read-only upstream","required_for_package":req,"used_for":"authorization, source, contract, or boundary context","notes":"Hashed before EXTRACT03; not modified."} for i,(b,p,req) in enumerate(specs,1)]
    auth_values=[("r1f_status",r1f.get("status"),"extract02a_r1f_artifact_consistency_fix_completed_authorized_for_extract03_package_preparation"),("r1f_authorization_value",r1f.get("authorization_value"),"authorized_to_prepare_extract03_execution_package"),("r1f_approved_count",r1f.get("human_freeze_items_approved_count"),10),("r1f_missing_count",r1f.get("missing_decisions_count"),0),("r1f_invalid_count",r1f.get("invalid_decisions_count"),0),("r1f_no_extraction",r1f.get("extraction_executed"),False),("r1f_no_K_d_D",f"{r1f.get('live_K_computed')}/{r1f.get('live_d_D_computed')}","False/False"),("r1f_no_clustering",r1f.get("clustering_executed"),False),("r1f_claim_boundary",r1f.get("physical_evidence_claim_made"),False),("r1f_previous_r1_inconsistency_classified",r1f.get("previous_r1_consistency_classification"),"internally_inconsistent_authorization_reporting")]
    authrows=[{"authorization_item":k,"source_artifact":rel(BLOCKS["R1F"]),"observed_value":v,"expected_value":e,"status":"pass" if str(v)==str(e) else "fail","blocking":"yes","notes":"Imported without mutation."} for k,v,e in auth_values]
    include=["F3_like_staged_delta_phi_spatial_pair_sources","phase_response_vector_sources","ordered_non_diagonal_pairs","x_index_response_vectors","wrapped_delta_phi_channel","raw_delta_phi_audit_channel"]
    exclude=["material_sensitive_sources","isotope_sensitive_sources","unverified_psi_state_families","unlineaged_loose_files","synthetic_evidence_sources","diagonal_pairs_as_physical_pairs"]
    source=[{"scope_id":f"E03-S{i:02d}","source_category":x,"include_or_exclude":"include","selection_rule":"metadata-selected F3 lineage and frozen HF-09 query","required_metadata":"source_id;run_id;lineage;unit_status;dimension_status","unit_dimension_requirement":"rad/dimensionless_angle; x=model_length_unit","lineage_requirement":"F3 staged source hash and run lineage","blocking_if_missing":"yes","notes":"Package contract only."} for i,x in enumerate(include,1)]
    source += [{"scope_id":f"E03-S{i+len(include):02d}","source_category":x,"include_or_exclude":"exclude","selection_rule":"exclude from first scope","required_metadata":"exclusion reason","unit_dimension_requirement":"not applicable","lineage_requirement":"record attempted source category","blocking_if_missing":"yes","notes":"No material or unlineaged expansion."} for i,x in enumerate(exclude,1)]
    axes=["source_id","run_id","pair_i","pair_j","x_index","channel","split_label","nullmodel_id","kernel_id"]
    channels=["raw_delta_phi","wrapped_delta_phi","cos_delta_phi","sin_delta_phi","abs_cos_delta_phi","phase_response_vector","K_candidate","d_cost_candidate","D_shortest_path_candidate","edge_strength_candidate","edge_candidate_flag","cluster_candidate_id","motif_candidate_id","validation_status"]
    future={"K_candidate","d_cost_candidate","D_shortest_path_candidate","edge_candidate_flag","cluster_candidate_id","motif_candidate_id"}
    tensor=[{"axis_or_channel_id":f"E03-T-{i:02d}","kind":"axis","name":x,"definition":"DWH tensor/datacube key axis","data_type":"text_or_integer_by_schema","required":"yes","unit_status":"not_applicable_or_inherited","dimension_status":"metadata-controlled","lineage_required":"yes","notes":"Schema contract."} for i,x in enumerate(axes,1)]
    tensor += [{"axis_or_channel_id":f"E03-C-{i:02d}","kind":"channel","name":x,"definition":"future computed output" if x in future else "source or derived contract channel","data_type":"real_or_identifier","required":"yes","unit_status":"declared before future execution","dimension_status":"declared before future execution","lineage_required":"yes","notes":"Not produced in this package step." if x in future else "Contract only; no live calculation."} for i,x in enumerate(channels,1)]
    prvals={"state_family":get(hf1,"state_family",hf1 if isinstance(hf1,str) else "not_supplied"),"primary_channel":get(hf1,"primary_channel","wrapped_delta_phi"),"audit_channel":get(hf1,"audit_channel","raw_delta_phi"),"window":get(hf1,"window","full frozen x_index range"),"ordering":get(hf1,"ordering","ordered non-diagonal pairs over x_index"),"normalization":get(hf1,"normalization","L2-normalize vectors"),"weights":get(hf1,"weights","uniform over x_index"),"zero_norm_policy":get(hf1,"zero_norm_policy","reject as validation failure"),"pair_diagonal_policy":"exclude","lineage_requirement":get(hf1,"lineage","F3 lineage required")}
    phase=[{"contract_id":f"E03-PR-{i:02d}","component":k,"definition":"frozen phase-response component","frozen_value_or_rule":v,"validation_requirement":"exact replay against human freeze and source metadata","blocking":"yes","notes":"No vector generated now."} for i,(k,v) in enumerate(prvals.items(),1)]
    kval=get(hf2,"construction_mode",hf2 if isinstance(hf2,str) else "K_from_phase_response_vectors")
    kparts={"K_mode":kval,"input_vectors":"frozen phase-response vectors","inner_product_definition":"K_ij=<psi_i|psi_j>","normalization":get(hf2,"normalization","use frozen normalized vectors"),"Hermiticity_check":get(hf2,"Hermiticity_check","required future validation"),"PSD_check":get(hf2,"PSD_check","required future validation"),"diagonal_policy":"validate K_ii under normalization","range_check":"validate normalized magnitude range","missing_vector_policy":"block future execution","claim_boundary":"correlation/Gram candidate; no physical evidence claim"}
    krows=[{"contract_id":f"E03-K-{i:02d}","component":k,"definition":"future Gram construction contract","frozen_value_or_rule":v,"validation_requirement":"must pass before result acceptance","blocking":"yes","notes":"No K computation."} for i,(k,v) in enumerate(kparts.items(),1)]
    dparts=[("ell_0","parameter",hf("HF-03"),"model cost scale","positive and not L2 theta","cost-distance candidate"),("epsilon_Gram","regularizer",hf("HF-04"),"dimensionless relative to normalized |K|","positive and <1","numerical regularizer only"),("d_ij_definition","d_ij := -ell_0 log(|K_ij| + epsilon_Gram)","frozen HF-03/HF-04","candidate cost","finite/range checks","not measured distance"),("D_ij_shortest_path_definition","D(i,j)=min_p sum d_ab","future graph input","candidate aggregate cost","future path validation","not proven geometry"),("s_ij_strength_transform",hf5,"ell_0", "dimensionless candidate strength","future range validation","relation-strength candidate"),("regularization_policy","use frozen epsilon_Gram; no post-hoc tuning",hf("HF-04"),"dimensionless","hash and freeze replay","no L2 repair"),("infinite_or_invalid_cost_policy","block and record validation failure","none","not applicable","no silent imputation","no claim"),("claim_boundary_cost_distance_not_geometry","D remains reconstructed cost-distance candidate","none","contract statement","mandatory wording","no emergent-geometry claim")]
    drows=[{"contract_id":f"E03-D-{i:02d}","quantity":q,"formula_or_rule":rule,"frozen_parameter":par,"unit_dimension_status":unit,"validation_requirement":vr,"claim_boundary":cb,"notes":"No d/D computation."} for i,(q,rule,par,unit,vr,cb) in enumerate(dparts,1)]
    edgeparts=[("theta_edge",hf("HF-06"),"future edge candidate","positive; frozen; not L2 theta"),("edge_candidate_rule","edge_strength_candidate >= theta_edge","future K/d/D output","validate deterministic application"),("edge_strength_source",hf5,"future d cost","validate frozen transform"),("post_hoc_tuning_forbidden","true","all future edge logic","reject parameter changes after results"),("L2_theta_not_reused","0.5 differs from 0.012446436850524916","theta_edge","hash replay")]
    edgerows=[{"contract_id":f"E03-E-{i:02d}","component":k,"frozen_value_or_rule":v,"applies_to":a,"validation_requirement":vr,"post_hoc_tuning_guard":"enforced","notes":"No edge construction."} for i,(k,v,a,vr) in enumerate(edgeparts,1)]
    kernels=hf7 if isinstance(hf7,list) else ["gram_distance_kernel","shortest_path_kernel","edge_candidate_kernel","cluster_dendrogram_kernel","motif_stability_kernel"]
    kernelrows=[{"kernel_id":f"E03-KER-{i:02d}","kernel_name":k,"purpose":"future guarded candidate computation","inputs_required":"validated frozen sources and predecessor outputs","outputs_planned":k.replace("kernel","candidate output"),"execution_status":"planned_not_executed","blocking_preconditions":"separate execution authorization; hash replay; dry-run gates","claim_boundary":"candidate result only","notes":"No kernel invoked."} for i,k in enumerate(kernels,1)]
    clusterparts=["distance_matrix_source","linkage_method","cluster_stability_check","split_bootstrap_protocol","cluster_to_motif_mapping","motif_id_generation","claim_boundary_candidate_grouping_only"]
    clusterrows=[{"protocol_id":f"E03-CL-{i:02d}","component":k,"frozen_value_or_rule":get(hf8,k.replace("claim_boundary_candidate_grouping_only","claim_boundary")),"input_required":"future validated D candidate","output_planned":"cluster/motif candidate metadata","execution_status":"planned_not_executed","claim_boundary":"candidate relational grouping only","notes":"No clustering or dendrogram."} for i,k in enumerate(clusterparts,1)]
    marts=["extract03_run","extract03_source_selection","extract03_tensor_axis","extract03_phase_response_vector_contract","extract03_K_candidate_result","extract03_distance_cost_candidate","extract03_shortest_path_candidate","extract03_edge_candidate","extract03_cluster_candidate","extract03_motif_candidate","extract03_validation_result","extract03_claim_boundary","extract03_lineage"]
    lineage=[{"mart_entity":m,"lineage_required":"yes","source_hash_required":"yes","unit_dimension_required":"yes","claim_boundary":"candidate/contract status must be explicit","write_allowed_in_package_step":"no","write_allowed_in_future_execution":"only after separate authorization","notes":"DDL is not executed."} for m in marts]
    modes=["package_preparation","dry_run_schema_validation","dry_run_source_selection","actual_extraction","actual_K_computation","actual_d_D_computation","actual_kernel_execution","actual_clustering","result_mart_write"]
    split=[{"execution_mode":m,"allowed_in_this_package":"yes" if m=="package_preparation" else "no","allowed_in_future_separate_execution":"not applicable" if m=="package_preparation" else "conditional","purpose":"write contracts" if m=="package_preparation" else "future guarded operation","required_authorization":"R1F package authorization" if m=="package_preparation" else "separate explicit execution authorization","forbidden_actions":"all live computation and writes" if m=="package_preparation" else "operation before gates pass","notes":"Modes remain separated."} for m in modes]
    plans=["upstream_artifacts","source_hub","metadata_db","f3_staging_db","extract02a_runs","extract02a_r1_runs","extract02a_r1f_runs","result_mart_future","output_directory_policy"]
    rollback=[{"plan_id":f"E03-NM-{i:02d}","component":x,"rule":"read-only now; hash before/after","rollback_strategy":"abort and invalidate isolated future outputs; never roll back by editing upstream","mutation_allowed_now":"no","mutation_allowed_future_execution":"isolated result mart only" if x=="result_mart_future" else "no","notes":"No mutation in package preparation."} for i,x in enumerate(plans,1)]
    guards=["no_extraction_now","no_live_K_now","no_live_d_D_now","no_shortest_paths_now","no_kernel_execution_now","no_clustering_now","no_result_mart_write_now","no_upstream_db_mutation","no_l2_repair","no_post_hoc_tuning","no_material_sensitive_sources","no_physical_evidence_claim","no_geometry_claim","no_gravity_claim"]
    guardrows=[{"guard_id":f"E03-G-{i:02d}","guard":g,"status":"pass","evidence":g+"=enforced","blocking_if_violated":"yes","notes":"Preparation-only code path."} for i,g in enumerate(guards,1)]
    gates=["R1F_authorization_imported","human_freeze_valid","F3_source_context_imported","source_selection_contract_written","tensor_schema_contract_written","K_contract_written","d_D_contract_written","edge_threshold_contract_written","kernel_plan_written","cluster_protocol_written","result_mart_contract_written","no_execution_guard_passed","claim_boundary_passed","exact_output_count"]
    gaterows=[{"gate_id":f"E03-AG-{i:02d}","gate":g,"required_for_package_completion":"yes","required_for_future_execution":"yes","status":"pass","blocking":"yes","notes":"Package gate only; future replay required."} for i,g in enumerate(gates,1)]
    validations=["source_hash_replay","human_freeze_replay","schema_header_validation","unit_dimension_validation","K_hermiticity_validation","K_PSD_validation","d_cost_range_validation","D_shortest_path_validation","edge_candidate_validation","cluster_stability_validation","claim_boundary_validation"]
    replay=[{"validation_id":f"E03-VR-{i:02d}","future_validation":v,"input_required":"frozen package plus future isolated inputs","expected_output":"explicit pass/fail and stop reason","run_now":"no","required_before_future_execution":"yes","notes":"Planned, not executed."} for i,v in enumerate(validations,1)]
    unsupported=["EXTRACT03 package proves QSB","EXTRACT03 package repairs L2 fail","EXTRACT03 package demonstrates emergent geometry","EXTRACT03 package demonstrates gravity","Package preparation equals extraction","Human freeze equals physical validation","K/d/D contract equals measured geometry","DWH metadata selection equals evidence"]
    claims=[{"statement_id":f"E03-CB-{i:02d}","statement":s,"classification":"unsupported_claim","safe_wording":"EXTRACT03 package preparation defines a guarded future execution route.","forbidden_wording":s,"notes":"Unsupported by package preparation."} for i,s in enumerate(unsupported,1)]

    OUT.mkdir(parents=True)
    manifest={"work_package":"QSB-EXTRACT03","status":"extract03_execution_package_preparation_completed_no_extraction","created_at_utc":datetime.now(timezone.utc).isoformat(),"repo_root":str(ROOT),"r1f_authorization_seen":True,"r1f_authorization_value":r1f["authorization_value"],"human_freeze_file_seen":True,"human_freeze_file_used":rel(inp),"human_freeze_items_reviewed":10,"human_freeze_items_approved":approved,"missing_decisions_count":missing_count,"invalid_decisions_count":invalid,"first_scope_ready_for_package":True,"material_sensitive_sources_in_first_scope":False,"package_preparation_only":True,"actual_extraction_authorized":False,"extraction_executed":False,"live_K_computed":False,"live_d_D_computed":False,"shortest_paths_computed":False,"kernels_executed":False,"clustering_executed":False,"result_mart_written":False,"upstream_modified":False,"physical_evidence_claim_made":False,"l2_fail_changed":False,"claim_boundary":"Contracts define a guarded future candidate-computation route; no extraction, evidence, geometry, gravity, or L2-repair claim follows.","next_allowed_action":"human_review_extract03_package_then_separately_authorize_execution","forbidden_next_action":"execute_extraction_now"}
    (OUT/"01_extract03_package_manifest.json").write_text(json.dumps(manifest,indent=2)+"\n")
    writecsv("02_upstream_inventory_and_hashes.csv",["artifact_id","upstream_block","path","exists","sha256","role","required_for_package","used_for","notes"],inventory)
    writecsv("03_authorization_import_review.csv",["authorization_item","source_artifact","observed_value","expected_value","status","blocking","notes"],authrows)
    writecsv("04_human_freeze_carry_forward_matrix.csv",["freeze_id","freeze_item","decision_value","decision_status","human_approval","blocks_extract03_package","blocks_actual_execution","carried_forward_to_extract03","package_role","validation_status","notes"],carried)
    writecsv("05_first_scope_source_selection_contract.csv",["scope_id","source_category","include_or_exclude","selection_rule","required_metadata","unit_dimension_requirement","lineage_requirement","blocking_if_missing","notes"],source)
    writecsv("06_tensor_datacube_schema_contract.csv",["axis_or_channel_id","kind","name","definition","data_type","required","unit_status","dimension_status","lineage_required","notes"],tensor)
    writecsv("07_phase_response_vector_contract.csv",["contract_id","component","definition","frozen_value_or_rule","validation_requirement","blocking","notes"],phase)
    writecsv("08_K_construction_contract.csv",["contract_id","component","definition","frozen_value_or_rule","validation_requirement","blocking","notes"],krows)
    writecsv("09_distance_cost_and_strength_contract.csv",["contract_id","quantity","formula_or_rule","frozen_parameter","unit_dimension_status","validation_requirement","claim_boundary","notes"],drows)
    writecsv("10_edge_threshold_contract.csv",["contract_id","component","frozen_value_or_rule","applies_to","validation_requirement","post_hoc_tuning_guard","notes"],edgerows)
    writecsv("11_kernel_execution_plan_no_run.csv",["kernel_id","kernel_name","purpose","inputs_required","outputs_planned","execution_status","blocking_preconditions","claim_boundary","notes"],kernelrows)
    writecsv("12_cluster_dendrogram_protocol_no_run.csv",["protocol_id","component","frozen_value_or_rule","input_required","output_planned","execution_status","claim_boundary","notes"],clusterrows)
    sql="-- CONTRACT ONLY. DO NOT EXECUTE IN EXTRACT03 PACKAGE PREPARATION.\n-- Candidate DDL for a separately authorized future result mart.\n"+"\n".join(f"CREATE TABLE {m} (record_id TEXT PRIMARY KEY, run_id TEXT NOT NULL, payload_json TEXT, validation_status TEXT, source_hash TEXT, claim_boundary TEXT);" for m in marts)+"\n"
    (OUT/"13_result_mart_schema_contract.sql").write_text(sql)
    writecsv("14_result_mart_lineage_and_claim_contract.csv",["mart_entity","lineage_required","source_hash_required","unit_dimension_required","claim_boundary","write_allowed_in_package_step","write_allowed_in_future_execution","notes"],lineage)
    writecsv("15_dry_run_vs_actual_execution_split.csv",["execution_mode","allowed_in_this_package","allowed_in_future_separate_execution","purpose","required_authorization","forbidden_actions","notes"],split)
    writecsv("16_no_mutation_and_rollback_plan.csv",["plan_id","component","rule","rollback_strategy","mutation_allowed_now","mutation_allowed_future_execution","notes"],rollback)
    writecsv("17_execution_guard_matrix.csv",["guard_id","guard","status","evidence","blocking_if_violated","notes"],guardrows)
    writecsv("18_acceptance_gate_matrix.csv",["gate_id","gate","required_for_package_completion","required_for_future_execution","status","blocking","notes"],gaterows)
    writecsv("19_validation_replay_plan.csv",["validation_id","future_validation","input_required","expected_output","run_now","required_before_future_execution","notes"],replay)
    writecsv("20_claim_boundary_matrix.csv",["statement_id","statement","classification","safe_wording","forbidden_wording","notes"],claims)
    (OUT/"21_future_execution_launch_checklist.md").write_text("# QSB-EXTRACT03 Launch Checklist\n\n## Vor Ausführung erneut prüfen\n- Paket- und Upstream-Hashes vollständig wiederholen.\n\n## Autorisierung\n- Separate explizite Ausführungsfreigabe verlangen.\n\n## Quellen und Hashes\n- F3-Quelle, Metadaten und Lineage verifizieren.\n\n## Human-Freeze\n- Alle zehn Entscheidungen unverändert erneut prüfen.\n\n## DWH- und Result-Mart-Grenzen\n- Nur isolierten Result-Mart-Vertrag verwenden.\n\n## No-Mutation / Rollback\n- Read-only-Upstream und Abbruchstrategie bestätigen.\n\n## Rechenpfad\n- Reihenfolge und Stop-Gates separat freigeben.\n\n## Claim-Grenzen\n- Kandidatenstatus und fehlende physikalische Validierung ausweisen.\n\n## Abbruchkriterien\n- Bei Hash-, Schema-, Unit-, Lineage- oder Validierungsfehler abbrechen.\n\n## Start nur nach separater Freigabe\nDieses Paket erlaubt noch keinen Start der Extraktion.\n")
    (OUT/"22_blocked_execution_stub.md").write_text("# QSB-EXTRACT03 Execution Guard\n\nBLOCKED: EXTRACT03 package preparation is not an extraction authorization.\n\nEine separate explizite Ausführungsfreigabe ist erforderlich.\n")
    (OUT/"23_short_package_note_de.md").write_text("# QSB-EXTRACT03 Kurznotiz\n\n## Ergebnis\nDas Ausführungspaket wurde ohne Extraktion vorbereitet.\n\n## Was vorbereitet wurde\nQuell-, Schema-, K/d/D-, Kernel-, Cluster-, Result-Mart-, Rollback- und Akzeptanzverträge.\n\n## Was nicht ausgeführt wurde\nKeine Extraktion, K/d/D-Berechnung, Pfadsuche, Kernel- oder Cluster-Ausführung und kein Result-Mart-Write.\n\n## Grenzen\nMaterial-sensitive Quellen bleiben ausgeschlossen; der L2-Fail bleibt unverändert; keine physikalische Evidenz- oder Geometrieaussage.\n\n## Nächster erlaubter Schritt\nMenschliche Paketprüfung und danach gegebenenfalls separate Ausführungsfreigabe.\n")
    (OUT/"FINAL_RESULT_NOTE.md").write_text("# QSB-EXTRACT03 Package Preparation Final Result\n\n## Status\n`extract03_execution_package_preparation_completed_no_extraction`\n\n## Authorization Imported\nR1F erlaubt ausschließlich die Vorbereitung dieses separaten Pakets.\n\n## Human-Freeze Carry-Forward\n10/10 Entscheidungen wurden gültig und nicht blockierend übernommen.\n\n## First Scope\nF3-artige Phase-Response-Quellen, geordnete nichtdiagonale Paare und x_index-Vektoren sind vertraglich vorbereitet.\n\n## Package Contents\nQuell-, Tensor-, K/d/D-, Edge-, Kernel-, Cluster-, Result-Mart-, Replay- und Rollback-Verträge wurden erstellt.\n\n## No-Execution Boundary\nKeine Extraktion oder Live-Berechnung und kein Datenbank-Write wurden ausgeführt.\n\n## Material-Sensitive Source Boundary\nMaterial-sensitive Quellen bleiben bis zu einem separaten Source Contract ausgeschlossen.\n\n## L2 Fail Boundary\nDer L2-Fail wurde weder verändert noch repariert oder neu interpretiert.\n\n## Claim Boundary\nDas Paket definiert nur einen kontrollierten zukünftigen Kandidatenpfad und liefert keine physikalische Validierung.\n\n## Next Allowed Action\nHuman review of the EXTRACT03 package. If accepted, create a separate explicit authorization for the actual EXTRACT03 execution run.\n")
    after={rel(p):sha(p) for _,p,_ in specs if p.is_file()}
    if before!=after:raise SystemExit("Upstream mutation detected")
    if len(list(OUT.iterdir()))!=24:raise SystemExit("Output count mismatch")
    print("status=extract03_execution_package_preparation_completed_no_extraction")
    print("r1f_authorization_imported=authorized_to_prepare_extract03_execution_package")
    print(f"reviewed=10 approved={approved} missing={missing_count} invalid={invalid}")
    print("execution=false\noutput_files=24")
if __name__=="__main__":raise SystemExit(main())
